### ISSUE TITLE
[Question] Where is xapic_initialize defined?

### ISSUE THREAD

**Issue by davidgmbb** [UWNetworksLab/arrakis#6]
Hello,

First I must say that both Arrakis and Barrelfish are such amazing projects and I think they bring some light into the operating system development scene which has been quite stuck in Windows and Linux. The multikernel approach seems very clever to me.

I have been reading the Arrakis and Barrelfish source code for a while to learn from it. In this process I haven't been able to clarify myself a doubt: in the APIC initialization code, there is a mention to xapic_* functions, which I haven't been able to see defined anywhere in the repository. One example of this is the function `xapic_initialize`. Searching through the Internet I haven't found it either. Is this some kind of autogenerated code hidden somewhere? I would appreciate your help.

Thanks a lot. I am sad that this has been discontinued...

I wish all the ex-members the best luck!

**Comment by simpeter** [comment]
Thanks for your message! The xapic_* functions are indeed generated - by
the Mackerel tool from xapic.dev files in the devices/ subdirectory.

**Comment by davidgmbb** [comment]
Thanks for the quick response!
I couldn't manage to build the project on Arch Linux, but I will boot a VM with Ubuntu and try. I will read the dev files. Thank you very much.
